import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, Braces, Check, CheckCircle2, Copy, X } from 'lucide-react'
import agentInstructions from '../../docs/PIXEL_LOOP_AGENT_INSTRUCTIONS.md?raw'
import {
  parseAnimationJson,
  type ParsedAnimation,
} from '../lib/importAnimationJson'

interface ImportAnimationDialogProps {
  onClose: () => void
  onImport: (animation: ParsedAnimation) => void
}

type ValidationResult =
  | { status: 'empty' }
  | { status: 'valid'; animation: ParsedAnimation }
  | { status: 'invalid'; message: string }

export function ImportAnimationDialog({ onClose, onImport }: ImportAnimationDialogProps) {
  const [source, setSource] = useState('')
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'error'>('idle')

  const validation = useMemo<ValidationResult>(() => {
    if (!source.trim()) return { status: 'empty' }
    try {
      return { status: 'valid', animation: parseAnimationJson(source) }
    } catch (error) {
      return {
        status: 'invalid',
        message: error instanceof Error ? error.message : 'Animation data is invalid.',
      }
    }
  }, [source])

  useEffect(() => {
    function handleEscape(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleEscape)
    return () => window.removeEventListener('keydown', handleEscape)
  }, [onClose])

  useEffect(() => {
    if (copyStatus === 'idle') return
    const timer = window.setTimeout(() => setCopyStatus('idle'), 2200)
    return () => window.clearTimeout(timer)
  }, [copyStatus])

  async function copyAgentInstructions() {
    try {
      if (!navigator.clipboard?.writeText) throw new Error('Clipboard unavailable')
      await navigator.clipboard.writeText(agentInstructions)
      setCopyStatus('copied')
    } catch {
      setCopyStatus('error')
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-[#10101d]/60 p-4 backdrop-blur-sm"
      role="presentation"
      onMouseDown={(event) => event.target === event.currentTarget && onClose()}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="import-animation-title"
        className="flex max-h-[90vh] w-full max-w-2xl flex-col overflow-hidden rounded-[28px] bg-white shadow-2xl"
      >
        <header className="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-5">
          <div className="flex items-start gap-3">
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-green-50 text-[#16a34a]">
              <Braces size={21} />
            </div>
            <div>
              <h2 id="import-animation-title" className="text-lg font-bold text-[#1a1a2e]">
                Import animation JSON
              </h2>
              <p className="mt-1 text-xs leading-5 text-slate-400">
                Paste a valid <code className="font-mono text-[#15803d]">pixel-loop/v1</code>{' '}
                object generated by your AI agent.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </header>

        <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">
          <label className="mb-2 block text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">
            Animation JSON
          </label>
          <textarea
            autoFocus
            value={source}
            onChange={(event) => setSource(event.target.value)}
            spellCheck={false}
            placeholder={'{\n  "format": "pixel-loop/v1",\n  "size": 16,\n  ...\n}'}
            aria-label="Animation JSON"
            className="min-h-72 w-full resize-y rounded-2xl border border-slate-200 bg-[#f8f8f5] p-4 font-mono text-xs leading-5 text-slate-700 outline-none transition focus:border-[#16a34a]/50 focus:ring-4 focus:ring-green-100"
          />

          {validation.status === 'invalid' && (
            <div
              role="alert"
              className="mt-3 flex items-start gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-xs leading-5 text-red-600"
            >
              <AlertCircle size={15} className="mt-0.5 shrink-0" />
              {validation.message}
            </div>
          )}

          {validation.status === 'valid' && (
            <div className="mt-3 rounded-xl border border-green-100 bg-green-50 p-3 text-[#15803d]">
              <div className="flex items-center gap-2 text-xs font-bold">
                <CheckCircle2 size={15} /> Ready to import
              </div>
              <div className="mt-2 flex flex-wrap gap-2 font-mono text-[10px]">
                <span className="summary-chip">
                  {validation.animation.resolution}×{validation.animation.resolution}
                </span>
                <span className="summary-chip">
                  {validation.animation.frames.length} frame
                  {validation.animation.frames.length === 1 ? '' : 's'}
                </span>
                <span className="summary-chip">{validation.animation.fps} FPS</span>
                <span className="summary-chip">
                  {Object.keys(validation.animation.palette).length} color
                  {Object.keys(validation.animation.palette).length === 1 ? '' : 's'}
                </span>
                <span className="summary-chip">
                  {validation.animation.transparentBackground ? 'transparent' : 'solid background'}
                </span>
              </div>
            </div>
          )}

          <p className="mt-3 text-[10px] leading-4 text-slate-400">
            Importing replaces the current canvas, frames, playback speed, and background after
            confirmation.
          </p>
        </div>

        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 bg-slate-50/70 px-6 py-4">
          <button
            type="button"
            onClick={() => void copyAgentInstructions()}
            className={`inline-flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-semibold transition ${
              copyStatus === 'error'
                ? 'text-red-500'
                : copyStatus === 'copied'
                  ? 'text-[#15803d]'
                  : 'text-slate-400 hover:bg-white hover:text-[#15803d]'
            }`}
          >
            {copyStatus === 'copied' ? <Check size={14} /> : <Copy size={14} />}
            {copyStatus === 'copied'
              ? 'Copied!'
              : copyStatus === 'error'
                ? 'Copy failed'
                : 'Copy agent instructions'}
          </button>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-500 hover:bg-slate-100"
            >
              Cancel
            </button>
            <button
              type="button"
              disabled={validation.status !== 'valid'}
              onClick={() => validation.status === 'valid' && onImport(validation.animation)}
              className="rounded-xl bg-[#16a34a] px-5 py-2.5 text-xs font-bold text-white shadow-lg shadow-green-700/15 transition hover:bg-[#15803d] disabled:cursor-not-allowed disabled:opacity-35"
            >
              Import animation
            </button>
          </div>
        </footer>
      </div>
    </div>
  )
}
